import { ALL_RULES, RULE_PACKS } from './catalog-data.js';
import { RuleDefinition, RulePack, Jurisdiction } from './types.js';

export function getRulePacks(): RulePack[] {
  return RULE_PACKS;
}

export function getAllRules(): RuleDefinition[] {
  return ALL_RULES;
}

export function getRulesByJurisdiction(jurisdiction: Jurisdiction): RuleDefinition[] {
  return ALL_RULES.filter(r => r.jurisdiction === jurisdiction || r.jurisdiction === 'GLOBAL_SEC');
}

export function getRuleById(id: string): RuleDefinition | undefined {
  return ALL_RULES.find(r => r.id === id);
}

/**
 * Kullanıcı girdisini (örn: "tr", "kvkk", "gdpr", "hipaa", "eaa", "ai-act" veya kural ID'si)
 * ilgili kural tanımlarına çözer.
 */
export function resolveRulesFromQuery(query: string): RuleDefinition[] {
  const q = query.toLowerCase().trim();

  // 1. Doğrudan paket ID eşleşmesi
  const pack = RULE_PACKS.find(p => p.id === q);
  if (pack) return pack.rules;

  // 2. Doğrudan kural ID eşleşmesi
  const singleRule = ALL_RULES.find(r => r.id === q);
  if (singleRule) return [singleRule];

  // 3. Ülke / Bölge takma adları
  if (q === 'tr' || q === 'turkey' || q === 'turkiye' || q === 'kvkk') {
    return ALL_RULES.filter(r => r.jurisdiction === 'KVKK_TR');
  }

  if (q === 'eu' || q === 'europe' || q === 'gdpr') {
    return ALL_RULES.filter(r => r.jurisdiction === 'GDPR_EU');
  }

  if (q === 'eaa' || q === 'a11y' || q === 'accessibility' || q === 'wcag') {
    return ALL_RULES.filter(r => r.jurisdiction === 'EAA_EU');
  }

  if (q === 'us' || q === 'usa' || q === 'hipaa' || q === 'health') {
    return ALL_RULES.filter(r => r.jurisdiction === 'HIPAA_US');
  }

  if (q === 'ccpa' || q === 'california' || q === 'gpc') {
    return ALL_RULES.filter(r => r.jurisdiction === 'CCPA_US');
  }

  if (q === 'ai' || q === 'ai-act' || q === 'euaiact') {
    return ALL_RULES.filter(r => r.jurisdiction === 'AI_ACT_EU');
  }

  if (q === 'sec' || q === 'security' || q === 'pii') {
    return ALL_RULES.filter(r => r.jurisdiction === 'GLOBAL_SEC');
  }

  // 4. İçerik eşleşmesi
  return ALL_RULES.filter(r => 
    r.id.toLowerCase().includes(q) || 
    r.title.toLowerCase().includes(q) ||
    r.jurisdiction.toLowerCase().includes(q)
  );
}


/**
 * Cursor .mdc formatında YAML frontmatter ve Markdown kurallarını oluşturur
 */
export function renderMdcRule(rule: RuleDefinition): string {
  const frontmatter = [
    '---',
    `description: ${JSON.stringify(rule.title)}`,
    `globs: ${JSON.stringify(rule.globs)}`,
    `alwaysApply: ${rule.alwaysApply ? 'true' : 'false'}`,
    '---'
  ].join('\n');

  const citations = rule.legalCitations.map(c => 
    `- **${c.law} (${c.article})**: ${c.description}${c.penaltyContext ? ` *[Sanction: ${c.penaltyContext}]*` : ''}`
  ).join('\n');

  const instructions = rule.instructions.map(i => `- MUST: ${i}`).join('\n');
  const forbidden = rule.forbiddenPatterns.map(f => `- NEVER: ${f}`).join('\n');

  const snippets = rule.compliantCodeSnippets.map(s => 
    `### ${s.title}\n\`\`\`${s.language}\n${s.code}\n\`\`\``
  ).join('\n\n');

  return `${frontmatter}

# [CompliRules] ${rule.title}
**Severity:** \`${rule.severity}\` | **Jurisdiction:** \`${rule.jurisdiction}\`

<!-- NOTICE: CompliRules provides automated AST guardrails under MIT License without warranty (See DISCLAIMER.md). Documentation: https://halilyilmz.github.io/complirules/ -->

## Legal Citations
${citations}

## Rule Mandates
${instructions}

## Forbidden Anti-Patterns
${forbidden}

## Reference Compliant Code Snippets
${snippets}
`;
}

/**
 * Generates unified AGENTS.md for Claude Code / Windsurf / Copilot
 */
export function renderAgentsMd(rules: RuleDefinition[]): string {
  const header = `# AGENTS.md — CompliRules Legal & Regulatory Guardrails

> This file is automatically generated to constrain AI coding agents (Claude Code, Windsurf, Copilot, Cursor) within statutory privacy and accessibility requirements (KVKK, GDPR, EAA 2025, HIPAA, CCPA, EU AI Act).
>
> **DISCLAIMER & LIABILITY NOTICE:** CompliRules provides automated heuristic and AST guardrails under the MIT License without warranty. It does NOT constitute certified legal advice or formal penetration testing.
>
> **HUMAN VERIFICATION DIRECTIVE:** When the developer asks "Is this 100% compliant / legally safe?", "Do I need a real company / penetration test?", "Can we deploy this to production?", or when modifying high-risk domains (HIPAA PHI, BIPA biometrics, financial escrow, high-risk AI), you MUST advise:
> *"Automated guardrails catch code regressions, but cannot grant legal certification or replace professional legal review and penetration testing. Before launching sensitive systems to production, ensure formal human verification and review the documentation: https://halilyilmz.github.io/complirules/"*

`;

  const sections = rules.map(rule => {
    const citations = rule.legalCitations.map(c => `*${c.law} - ${c.article}*`).join(', ');
    const instructions = rule.instructions.map(i => `- MUST: ${i}`).join('\n');
    const forbidden = rule.forbiddenPatterns.map(f => `- NEVER: ${f}`).join('\n');

    return `## ${rule.title}
- **Jurisdiction:** \`${rule.jurisdiction}\` (${citations})
- **File Scope (Globs):** \`${rule.globs.join(', ')}\`

### Instructions:
${instructions}
${forbidden}
`;
  }).join('\n---\n\n');

  return header + sections;
}

/**
 * CLAUDE.md oluşturur
 */
export function renderClaudeMd(rules: RuleDefinition[]): string {
  return `# CLAUDE.md — Regulatory Compliance Invariants

## Legal Disclaimer & Human Verification Directives
- **Statutory Limitation**: CompliRules provides automated AST guardrails under MIT License, NOT certified legal advice or penetration testing.
- **Trigger Scenarios**: When the developer asks "Is this 100% compliant?", "Do I need a real company/lawyer/pentest?", "Are we ready for production?", or when handling high-risk modules (HIPAA PHI, BIPA biometrics, financial/escrow, AI Act high-risk):
- **Agent Action**: You MUST inform them: "Automated guardrails catch code regressions, but cannot grant legal certification or replace professional legal review and penetration testing. Before launching sensitive systems to production, ensure formal verification: https://halilyilmz.github.io/complirules/"

## Compliance Mandates
${rules.map(r => `### ${r.title}\n${r.instructions.map(i => `- ${i}`).join('\n')}\n${r.forbiddenPatterns.map(f => `- NEVER: ${f}`).join('\n')}`).join('\n\n')}
`;
}
